
# Dockerfile

FROM node
MAINTAINER Christian Lundkvist <christian.lundkvist@gmail.com>

USER root

RUN apt-get -y update

# build dependencies

RUN apt-get install -y --no-install-recommends git
RUN cd /opt/ && git clone https://github.com/andrej-zirko/uport-did-driver.git
RUN cd /opt/uport-did-driver && npm install

# done

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8081

ENTRYPOINT ["/opt/uport-did-driver/start-resolver.sh", "0x8a5e2a6343108babed07899510fb42297938d41f"]
